// vue-todo/src/components/TodoList.vue
<template>
  <div class="todo">
    <h3>ToDo List</h3>
    <input type="text" placeholder="New Task" v-model="newTask" @keyup.enter="addTask"/>
    <button @click="addTask()">Add</button>
    <ul v-for="(task, index) in tasks" :key="task.id">
      <input type="checkbox" v-model="task.completed" @click="toggleTaskStatus(task)">
      {{task.title}}
      <a class="red" @click="removeTask(index)">X</a>
    </ul>
  </div>
</template>

<script>
  export default {
    name: "TodoList",
    data () {
      return {
        newTask: '',
        tasks:[
          {
            'id':1,
            'title':'Task 1',
            'completed': true
          },
          {
            'id':2,
            'title':'Task 2',
            'completed': true
          },
          {
            'id':3,
            'title':'Task 3',
            'completed': false
          }
        ],
        taskId: 0,
      }
    },
    mounted: function () {
      this.taskId = this.tasks[this.tasks.length-1].id;
    },
    methods:{
      addTask(){
        this.taskId += 1;
        if (this.newTask.trim().length === 0){
          this.newTask = 'Task ' + this.taskId;
        }
        this.tasks.push({
          id:this.taskId,
          title:this.newTask,
          completed: false
        });
        this.newTask='';
      },
      removeTask(index){
        this.tasks.splice(index,1);

      },
      toggleTaskStatus(index){
        this.tasks[index].completed = !this.tasks[index].completed;

      }
    }
  }
</script>

<style scoped>
  h3{
    text-align: center;
  }
  .red{
    color: red;
  }
</style>

// react-todo/src/TodoList.js
import React from "react";

class TodoList extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            newTask: '',
            tasks:[
                {
                    'id':1,
                    'title':'Task 1',
                    'completed': true
                },
                {
                    'id':2,
                    'title':'Task 2',
                    'completed': true
                },
                {
                    'id':3,
                    'title':'Task 3',
                    'completed': false
                }
            ]
        };
        this.taskId = this.getTail(this.state.tasks).id;
    }
    render() {
        return (
            <div className="todo">
                <input type="text" placeholder="New Task" value={this.state.newTask}
                       onChange={e => this.setState({ "newTask": e.target.value})}/>
                <button onClick={() => this.addTask()}>Add</button>
                <ul>
                    {this.state.tasks.map((task, index) => {
                        return (
                            <p>
                                <input type="checkbox" checked={task.completed} onClick={() => this.toggleTaskStatus(index)} />
                                {task.title}
                                <span className="red" onClick={() => this.removeTask(index)}> X</span>
                            </p>
                        )
                    })}
                </ul>
            </div>
        );
    }
    addTask(){
        this.taskId += 1;
        let updatedList = this.state.tasks;
        let newTask = {
            id:this.taskId,
            title:this.state.newTask,
            completed: false
        };

        if (newTask.title.trim().length === 0){
            newTask.title = 'Task ' + this.taskId;
        }

        updatedList.push(newTask);
        this.setState({ "newTask": '', "tasks": updatedList});
    }
    removeTask(index){
        let updatedList = this.state.tasks;
        updatedList.splice(index,1);
        this.setState({ "tasks": updatedList});
    }
    toggleTaskStatus(index){
        let updatedList = this.state.tasks;
        updatedList[index].completed = !updatedList[index].completed;
        this.setState({ "tasks": updatedList});
    }
    getLastIndex(array){
        return array.length-1;
    }
    getTail(array){
        return array[this.getLastIndex(array)];
    }
}

export default TodoList;
