// angular-todo/src/app/todolist/todolist.component.ts
import { Component, OnInit } from '@angular/core';
import {FormControl} from '@angular/forms';

@Component({
  selector: 'app-todolist',
  template: `
    <h3>ToDo List</h3>
    <input #task type="text" [placeholder]="'New Task'" [formControl]="inputField">
    <button (click)="addTask()">Add</button>
    <ul *ngFor="let task of tasks; index as i">
      <input type="checkbox" [checked]="task.completed" (click)="toggleTaskStatus(task)"> {{task.title}} <a
      [style.color]="'red'" (click)="removeTask(i)">X</a>
    </ul>`,
  styles: [`
    h3{
      text-align: center;
    }`]
})
export class TodolistComponent implements OnInit {
  public inputField = new FormControl('');
  public tasks = [
    {
      id: 1,
      title: 'Task 1',
      completed: true
    },
    {
      id: 2,
      title: 'Task 2',
      completed: true
    },
    {
      id: 3,
      title: 'Task 3',
      completed: false
    }
  ];
  public count = this.tasks.length;
  constructor() { }

  ngOnInit(): void {
  }

  addTask(): void{
    this.count += 1;
    const taskTitle = this.inputField.value || 'Task ' + this.count;
    const newTask = {id: this.count, title: taskTitle, completed: false};
    this.tasks.push(newTask);
    this.inputField.reset();
  }

  removeTask(index): void{
    if (index > -1) {
      this.tasks.splice(index, 1);
    }
  }

  toggleTaskStatus(task: any) {
    task.completed = !task.completed;
  }
}

// vue-todo/src/components/TodoList.vue
<template>
  <div class="todo">
    <h3>ToDo List</h3>
    <input type="text" placeholder="New Task" v-model="newTask" @keyup.enter="addTask"/>
    <button @click="addTask()">Add</button>
    <ul v-for="(task, index) in tasks" :key="task.id">
      <input type="checkbox" v-model="task.completed" @click="toggleTaskStatus(task)">
      {{task.title}}
      <a class="red" @click="removeTask(index)">X</a>
    </ul>
  </div>
</template>

<script>
  export default {
    name: "TodoList",
    data () {
      return {
        newTask: '',
        tasks:[
          {
            'id':1,
            'title':'Task 1',
            'completed': true
          },
          {
            'id':2,
            'title':'Task 2',
            'completed': true
          },
          {
            'id':3,
            'title':'Task 3',
            'completed': false
          }
        ],
        taskId: 0,
      }
    },
    mounted: function () {
      this.taskId = this.tasks[this.tasks.length-1].id;
    },
    methods:{
      addTask(){
        this.taskId += 1;
        if (this.newTask.trim().length === 0){
          this.newTask = 'Task ' + this.taskId;
        }
        this.tasks.push({
          id:this.taskId,
          title:this.newTask,
          completed: false
        });
        this.newTask='';
      },
      removeTask(index){
        this.tasks.splice(index,1);

      },
      toggleTaskStatus(index){
        this.tasks[index].completed = !this.tasks[index].completed;

      }
    }
  }
</script>

<style scoped>
  h3{
    text-align: center;
  }
  .red{
    color: red;
  }
</style>
