// angular-todo/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <div>
        <app-todolist></app-todolist>
    </div>`,
  styles: [`
    div{
      display: flex;
      flex-direction: column;
      align-items: center;
    }`]
})
export class AppComponent {
  title = 'angular-todo';
}

// vue-todo/src/App.vue
<template>
  <div id="app">
    <TodoList/>
  </div>
</template>

<script>
  import TodoList from "./components/TodoList";

  export default {
    name: 'App',
    components: {
      TodoList
    }
  }
</script>

<style>
  #app {
    display: flex;
    flex-direction: column;
    align-items: center;
  }
</style>
